remote_theme: mmistakes/minimal-mistakes

search_enabled: true

# Reading Files
include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

## mimic GitHub Pages with --safe
#whitelist:
#  - jekyll-paginate
#  - jekyll-sitemap
#  - jekyll-gist
#  - jekyll-feed
#  - jekyll-include-cache
